import React from "react"
import PropTypes from 'prop-types';
import { withStyles } from '@material-ui/core/styles';
import Grid from '@material-ui/core/Grid';
import Paper from '@material-ui/core/Paper';
import Typography from '@material-ui/core/Typography';
import ButtonBase from '@material-ui/core/ButtonBase';
import Switch from '@material-ui/core/Switch';

import quick from "../../../assets/quick.png"
import custom from "../../../assets/custom.png"
import placement from "../../../assets/placement.png"

const styles = theme => ({
    root: {
        marginTop: 10,
        flexGrow: 1,
        maxWidth: 700,
        padding: theme.spacing.unit * 2,
    },
    image: {
        width: 128,
        height: 128,
    },
    img: {
        margin: 'auto',
        display: 'block',
        maxWidth: '100%',
        maxHeight: '100%',
    },
});

class EvalutaionMethods extends React.Component {
    constructor(props) {
        super(props)
    }

    state = {
        checkedA: true,
        checkedB: false,
    }


    handleChange = name => event => {
        this.setState({ [name]: event.target.checked });
    };

    render() {
        const { classes } = this.props;
        return (
            <div>
                <Typography variant="subheading">
                    We are almost done! You can also select which evalution strategies you can provide for your students.
                </Typography>
                <Paper className={classes.root}>
                    <Grid container spacing={16} style={{ alignItems: "center" }}>
                        <Grid item>
                            <ButtonBase className={classes.image}>
                                <img className={classes.img} alt="complex" src={quick} />
                            </ButtonBase>
                        </Grid>
                        <Grid container item xs={12} sm container>
                            <Grid item xs container direction="column" spacing={16}>
                                <Grid item xs>
                                    <Typography gutterBottom variant="title">
                                        Quick Test
                            </Typography>
                                    <Typography gutterBottom variant="subheading" align="justify">
                                    Enable this feature if you want to provide a quick test for your students to 
                                    evaluate their learning while using the tutor. This test can be automatically
                                    generated by the tutor every time a student wants to test her current knowledge.
                            </Typography>
                                </Grid>
                            </Grid>
                        </Grid>
                        <Grid justify="center" alignItems="center" >
                            <Switch
                                checked={this.state.checkedA}
                                onChange={this.handleChange('checkedA')}
                                value="checkedA"
                                color="primary"
                            />
                        </Grid>
                    </Grid>
                </Paper>
                <Paper className={classes.root}>
                    <Grid container spacing={16} style={{ alignItems: "center" }}>
                        <Grid item>
                            <ButtonBase className={classes.image}>
                                <img className={classes.img} alt="complex" src={custom} />
                            </ButtonBase>
                        </Grid>
                        <Grid container item xs={12} sm container>
                            <Grid item xs container direction="column" spacing={16}>
                                <Grid item xs>
                                    <Typography gutterBottom variant="title">
                                        Custom Test
                            </Typography>
                                    <Typography gutterBottom variant="subheading" align="justify">
                                    Enable this feature if you want to provide a customized test for your students 
                                    to evaluate their learning while using the tutor. In this test your student will 
                                    be able to select which subjects she wants to test.
                            </Typography>
                                </Grid>
                            </Grid>
                        </Grid>
                        <Grid justify="center" alignItems="center" >
                            <Switch
                                checked={this.state.checkedB}
                                onChange={this.handleChange('checkedB')}
                                value="checkedB"
                                color="primary"
                            />
                        </Grid>
                    </Grid>
                </Paper>
                <Paper className={classes.root}>
                    <Grid container spacing={16} style={{ alignItems: "center" }}>
                        <Grid item>
                            <ButtonBase className={classes.image}>
                                <img className={classes.img} alt="complex" src={placement} />
                            </ButtonBase>
                        </Grid>
                        <Grid container item xs={12} sm container>
                            <Grid item xs container direction="column" spacing={16}>
                                <Grid item xs>
                                    <Typography gutterBottom variant="title">
                                        Placement Test
                            </Typography>
                                    <Typography gutterBottom variant="subheading" align="justify">
                                    Enable this feature if you want to define a test for your students to evaluate 
                                    more advanced subjects that have not been studied yet. If the student is approved 
                                    in the test, she will have her knowledge level updated to include learning about
                                    such objects.
                            </Typography>
                                </Grid>
                            </Grid>
                        </Grid>
                        <Grid justify="center" alignItems="center" >
                            <Switch
                                checked={this.state.checkedB}
                                onChange={this.handleChange('checkedB')}
                                value="checkedB"
                                color="primary"
                            />
                        </Grid>
                    </Grid>
                </Paper>
            </div>
        )
    }
}

EvalutaionMethods.propTypes = {
    classes: PropTypes.object.isRequired,
};

export default withStyles(styles)(EvalutaionMethods)