import React, { Component } from "react";
import PropTypes from "prop-types";
import { withStyles } from "@material-ui/core/styles";
import { Grid, Card, Typography, Switch } from "@material-ui/core";

import quick from "../../../assets/quick.png";
import custom from "../../../assets/custom.png";
import placement from "../../../assets/placement.png";

const styles = theme => ({
  root: {
    flexGrow: 1,
    maxWidth: "100%",
    padding: theme.spacing.unit * 2,
    [theme.breakpoints.down('sm')]: {
      padding: 1,
      marginTop: 10,
      marginBottom: 20
    },
  },
  gridCard: {
    alignItems: 'center',
    [theme.breakpoints.down('sm')]: {
      justifyContent: 'center'
    },
  },
  gridText: {
    [theme.breakpoints.down('sm')]: {
      justifyContent: 'center'
    },
  },
  title: {
    [theme.breakpoints.down('sm')]: {
      fontSize: '0.9rem'
    },
  },
  titleCard: {
    fontWeight: 'bold',
    [theme.breakpoints.down('sm')]: {
      fontSize: '0.9rem',
      textAlign: 'center'
    },
  },
  textCard: {
    [theme.breakpoints.down('sm')]: {
      fontSize: '0.8rem'
    },
  },
  image: {
    width: 128,
    height: 128
  },
  img: {
    width: 123
  }
});

class EvalutaionMethods extends Component {
  constructor(props) {
    super(props);
  }

  state = {
    checkedA: true,
    checkedB: false,
    checkedC: false,

  };

  handleChange = name => event => {
    this.setState({ [name]: event.target.checked });
  };

  render() {
    const { classes } = this.props;
    return (
      <div style={{ justifyContent: "center" }}>
        <Typography className={classes.title} variant="subtitle1">
          We are almost done! You can also select which evalution strategies you
          can provide for your students.
        </Typography>
        <div className={classes.root}>
          <Card>
            <Grid container style={{ padding: 20 }}>
              <Grid item xs={12}>
                <Grid
                  container
                  direction="row"
                  spacing={16}
                  className={classes.gridCard}
                >
                  <img className={classes.img} alt="complex" src={quick} />
                  <Grid className={classes.gridText} container item xs={12} sm container>
                    <Grid item xs container direction="column" spacing={16}>
                      <Grid item xs>
                        <Typography className={classes.titleCard} gutterBottom variant="h6">
                          Quick Test
                        </Typography>
                        <Typography
                          gutterBottom
                          variant="subtitle1"
                          
                          className={classes.textCard}
                        >
                          Enable this feature if you want to provide a quick
                          test for your students to evaluate their learning
                          while using the tutor. This test can be automatically
                          generated by the tutor every time a student wants to
                          test her current knowledge.
                        </Typography>
                      </Grid>
                    </Grid>
                  </Grid>
                  <Switch
                    checked={this.state.checkedA}
                    onChange={this.handleChange("checkedA")}
                    value="checkedA"
                    color="primary"
                  />
                </Grid>
              </Grid>
            </Grid>
          </Card>
        </div>
        <div className={classes.root}>
          <Card>
            <Grid container style={{ padding: 20 }}>
              <Grid item xs={12}>
                <Grid
                  container
                  direction="row"
                  spacing={16}
                  className={classes.gridCard}
                >
                  <img className={classes.img} alt="complex" src={custom} />
                  <Grid className={classes.gridText} container item xs={12} sm container>
                    <Grid item xs container direction="column" spacing={16}>
                      <Grid item xs>
                        <Typography className={classes.titleCard} gutterBottom variant="h6">
                          Custom Test
                        </Typography>
                        <Typography
                          gutterBottom
                          variant="subtitle1"
                          
                          className={classes.textCard}
                        >
                          Enable this feature if you want to provide a
                          customized test for your students to evaluate their
                          learning while using the tutor. In this test your
                          student will be able to select which subjects she
                          wants to test.
                        </Typography>
                      </Grid>
                    </Grid>
                  </Grid>
                  <Switch
                    checked={this.state.checkedB}
                    onChange={this.handleChange("checkedB")}
                    value="checkedB"
                    color="primary"
                  />
                </Grid>
              </Grid>
            </Grid>
          </Card>
        </div>
        <div className={classes.root}>
          <Card>
            <Grid container style={{ padding: 20 }}>
              <Grid item xs={12}>
                <Grid
                  container
                  direction="row"
                  spacing={16}
                  className={classes.gridCard}
                >
                  <img className={classes.img} alt="complex" src={placement} />
                  <Grid className={classes.gridText} container item xs={12} sm container>
                    <Grid item xs container direction="column" spacing={16}>
                      <Grid item xs>
                        <Typography className={classes.titleCard} gutterBottom variant="h6">
                          Placement Test
                        </Typography>
                        <Typography
                          gutterBottom
                          variant="subtitle1"
              
                          className={classes.textCard}
                        >
                          Enable this feature if you want to define a test for
                          your students to evaluate more advanced subjects that
                          have not been studied yet. If the student is approved
                          in the test, she will have her knowledge level updated
                          to include learning about such objects.
                        </Typography>
                      </Grid>
                    </Grid>
                  </Grid>
                  <Switch
                    checked={this.state.checkedC}
                    onChange={this.handleChange("checkedC")}
                    value="checkedC"
                    color="primary"
                  />
                </Grid>
              </Grid>
            </Grid>
          </Card>
        </div>
      </div>
    );
  }
}

EvalutaionMethods.propTypes = {
  classes: PropTypes.object.isRequired
};

export default withStyles(styles)(EvalutaionMethods);
